// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBba_VyIgChRVJ8jIL6cUV6oxqk1oVNJZg',
    appId: '1:236719719760:web:a0e267bbf205507029d855',
    messagingSenderId: '236719719760',
    projectId: 'event-app-edd99',
    authDomain: 'event-app-edd99.firebaseapp.com',
    storageBucket: 'event-app-edd99.firebasestorage.app',
    measurementId: 'G-4WTW8KJ1CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Zxuu6IlK0le3LJ3VMF_02pnt5MMuzDg',
    appId: '1:236719719760:android:6b969e58138b452729d855',
    messagingSenderId: '236719719760',
    projectId: 'event-app-edd99',
    storageBucket: 'event-app-edd99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd92tWULVEmCyNmeG5x-2cgt2ukUkxrIg',
    appId: '1:236719719760:ios:e73417128ba77a5029d855',
    messagingSenderId: '236719719760',
    projectId: 'event-app-edd99',
    storageBucket: 'event-app-edd99.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd92tWULVEmCyNmeG5x-2cgt2ukUkxrIg',
    appId: '1:236719719760:ios:e73417128ba77a5029d855',
    messagingSenderId: '236719719760',
    projectId: 'event-app-edd99',
    storageBucket: 'event-app-edd99.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBba_VyIgChRVJ8jIL6cUV6oxqk1oVNJZg',
    appId: '1:236719719760:web:3dc0d4e767505bb229d855',
    messagingSenderId: '236719719760',
    projectId: 'event-app-edd99',
    authDomain: 'event-app-edd99.firebaseapp.com',
    storageBucket: 'event-app-edd99.firebasestorage.app',
    measurementId: 'G-CWFTLXB5Q8',
  );
}
